(cl:defpackage multi_map_server-msg
  (:use )
  (:export
   "<MULTIOCCUPANCYGRID>"
   "MULTIOCCUPANCYGRID"
   "<SPARSEMAP3D>"
   "SPARSEMAP3D"
   "<MULTISPARSEMAP3D>"
   "MULTISPARSEMAP3D"
   "<VERTICALOCCUPANCYGRIDLIST>"
   "VERTICALOCCUPANCYGRIDLIST"
  ))

