#define MAVLINK_MSG_ID_HIGHRES_IMU 105
#define MAVLINK_MSG_ID_LOCAL_POSITION_NED 32
#define MAVLINK_MSG_ID_ATTITUDE 30
#define MAVLINK_MSG_ID_ALTITUDE 000
#define MAVLINK_MSG_ID_EXTENDED_SYS_STATE 245
#define MAVLINK_MSG_ID_GPS_GLOBAL_ORIGIN 49
#define MAVLINK_MSG_ID_HOME_POSITION 242
#define MAVLINK_MSG_ID_RC_CHANNELS 65
#define MAVLINK_MSG_ID_SYSTEM_TIME 2


