#define SYS_STATUS 1
#define GPS_RAW_INT 24
#define ATTITUDE 30
#define ATTITUDE_QUATERNION 31
#define LOCAL_POSITION_NED 32
#define GLOBAL_POSITION_INT 33
#define RC_CHANNELS_RAW 35
#define RC_CHANNELS 65
#define ATTITUDE_TARGET 83
#define POSITION_TARGET_LOCAL_NED 85
#define HIGHRES_IMU 105
#define DISTANCE_SENSOR 132

#define EXTENDED_SYS_STATE 245
#define GPS_GLOBAL_ORIGIN 49
#define HOME_POSITION 242
#define SYSTEM_TIME 2


