(cl:defpackage quadrotor_msgs-msg
  (:use )
  (:export
   "<SERIAL>"
   "SERIAL"
   "<AUXCOMMAND>"
   "AUXCOMMAND"
   "<POSITIONCOMMAND>"
   "POSITIONCOMMAND"
   "<CORRECTIONS>"
   "CORRECTIONS"
   "<STATUSDATA>"
   "STATUSDATA"
   "<SO3COMMAND>"
   "SO3COMMAND"
   "<PPROUTPUTDATA>"
   "PPROUTPUTDATA"
   "<TRPYCOMMAND>"
   "TRPYCOMMAND"
   "<OUTPUTDATA>"
   "OUTPUTDATA"
   "<GAINS>"
   "GAINS"
  ))

