(cl:in-package quadrotor_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          QUAD_TIME-VAL
          QUAD_TIME
          DES_THRUST-VAL
          DES_THRUST
          DES_ROLL-VAL
          DES_ROLL
          DES_PITCH-VAL
          DES_PITCH
          DES_YAW-VAL
          DES_YAW
          EST_ROLL-VAL
          EST_ROLL
          EST_PITCH-VAL
          EST_PITCH
          EST_YAW-VAL
          EST_YAW
          EST_ANGVEL_X-VAL
          EST_ANGVEL_X
          EST_ANGVEL_Y-VAL
          EST_ANGVEL_Y
          EST_ANGVEL_Z-VAL
          EST_ANGVEL_Z
          EST_ACC_X-VAL
          EST_ACC_X
          EST_ACC_Y-VAL
          EST_ACC_Y
          EST_ACC_Z-VAL
          EST_ACC_Z
          PWM-VAL
          PWM
))